def chart = api.newChartBuilder()
        .newTimeSeries()
        .getOptions()
        .setTitle('Revenue and Margin % in Time')
        .setSubtitle(input.CustomerId ? "Filter by customer ${input.CustomerId}" : null)
        .setComparison(false)
        .setHideLegend(false)
        .setHideTooltips(false)
        .setDisableDrilldown(false)
        .setDisableZoom(false)
        .setXLabel('Quarter')
        .setYLabel('Revenue')
        .setShowZAxis(false)
        .setZLabel('Margin %')
        .setLegacyComparisonMode(false)
        .setBoxplotAxisLabel('Box Plot')
        .back()
        .addSeries()
        .setLabel('Transactions')
        .setDatamart('DM.Transactions')
        .setCurrency('EUR')
        .setHideDataLabels(true)
        .setAxisX('InvoiceDateQuarter')
        .setAxisY('ListPrice').withTotal().back()
        .setType(SeriesType.BAR)
        .addDimFilter('InvoiceDateYear', input.Year)
        .addDimFilter('CustomerId', input.CustomerId)
        .addAdditionalMeasure()
        .setMeasure('Margin')
        .setId(1)
        .withTotal()
        .withBoxplotField()
        .setType(SeriesType.LINE)
        .back()
        .back()

        .getDictionary()
        .buildFromOpaqueString('[{"sectionIdx":1,"category":"PROJECTION","categoryLabel":"Projection","defaultValue":"Invoice Date Quarter","field":{"name":"InvoiceDateQuarter","rank":38,"functionalType":"TIMEDIMENSION","visibility":1,"source":"DMDS.cal","sourceField":"CalQuarter","expression":"InvoiceDateQuarter","system":true,"key":false,"deployed":true,"dimension":true,"queryable":true,"persisted":true,"calculated":false,"aggregation":false,"auxiliary":false,"partitioningKey":false,"distributionKey":false,"numeric":false,"type":"TEXT","owningFC":"[System]","time":true,"messages":{},"label":"Invoice Date Quarter"},"key":"x","keyLabel":"Axis X","sectionLabel":"Transactions","seriesIndex":0,"value":"Quarter"},{"sectionIdx":1,"category":"PROJECTION","categoryLabel":"Projection","defaultValue":"∑List Price","field":{"name":"ListPrice","rank":7,"measureType":"PERUNIT","functionalType":"PERCENTBASIS","visibility":1,"source":"DMDS.Transaction","sourceField":"ListPrice","expression":"ListPrice","system":false,"key":false,"deployed":true,"dimension":false,"queryable":true,"persisted":true,"calculated":false,"aggregation":false,"auxiliary":false,"partitioningKey":false,"distributionKey":false,"numeric":true,"type":"MONEY","owningFC":"Transaction","time":false,"messages":{},"label":"List Price"},"key":"y","keyLabel":"Axis Y","sectionLabel":"Transactions","seriesIndex":0,"value":"Revenue"},{"sectionIdx":1,"category":"PROJECTION","categoryLabel":"Projection","defaultValue":"∑Margin","field":{"name":"Margin","rank":19,"visibility":1,"expression":"InvoicePrice - Cost","system":false,"key":false,"deployed":false,"dimension":false,"queryable":true,"persisted":false,"calculated":true,"aggregation":false,"auxiliary":false,"partitioningKey":false,"distributionKey":false,"numeric":true,"type":"MONEY","time":false,"messages":{},"label":"Margin"},"key":"m1","keyLabel":"Measure 1","sectionLabel":"Transactions","seriesIndex":0,"id":1}]')
        .back()
        .build()